# Generated by Django 5.2.5 on 2025-08-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='decription',
            new_name='description',
        ),
    ]
